note = []
username = input("Введите имя пользователя: ")
note.append(username)
content = input("Введите описание заметки: ")
note.append(content)
status = input("Введите статус заметки: ")
note.append(status)
created_date = input("Введите дату создания заметки (дд-мм-гггг): ")
note.append(created_date)
issue_date = input("Введите дату истечения заметки (дд-мм-гггг): ")
note.append(issue_date)
titles = []
title1 = input("Введите первый заголовок заметки: ")
titles.append(title1)
title2 = input("Введите второй заголовок заметки: ")
titles.append(title2)
title3 = input("Введите третий заголовок заметки: ")
titles.append(title3)
note.append(titles)
print("Имя пользователя:", note[0])
print("Описание заметки:", note[1])
print("Статус заметки:", note[2])
print("Дата создания заметки:", note[3])
print("Дата истечения заметки:", note[4])
print("Заголовки заметки:", note[5])
